---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: kube # building the API docker image
    image: gcr.io/cloud-builders/gcloud
    commands:
      - echo ${DRONE_COMMIT_SHA:0:7}
      - echo ${gcpkey}
    when:
      target:
        exclude:
          - production

---
kind: secret
name: gcpkey
get:
  path: secret/data/drone/gcp
  name: test