---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: serverless # building the API docker image
    image: gcr.io/cloud-builders/gcloud
    environment:
      gcpkey:
        from_secret: gcpkey
    commands:
      - echo ${DRONE_COMMIT_SHA:0:7}
      - echo $gcpkey
      - printenv
    when:
      target:
        exclude:
          - production
---
kind: secret
name: gcpkey
get:
  path: secret/data/drone/gcp
  name: test