---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: serverless # building the API docker image
    image: gcr.io/cloud-builders/gcloud
    environment:
      GCPKEY:
        from_secret: gcpkey
    commands:
      - 'echo "$GCPKEY" >> ~/keyfile.json'
      - gcloud auth activate-service-account --key-file ~/keyfile.json
      - gcloud functions deploy gleich_switch --runtime=python37 --project main-285019 --trigger-topic=gleich-tech

---
kind: secret
name: gcpkey
get:
  path: secret/data/drone/gcp
  name: keyfile.json