service: gleich-tech-switch

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-west2
  project: main-285019
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json

frameworkVersion: '2'
plugins:
  - serverless-google-cloudfunctions
  - serverless-python-requirements
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  switch:
    handler: handler
    events:
      - http: path

custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.7
    pythonBin: python3.7